name: Daily Update

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Update
        run: node daily.js
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "bot@github.com"
          git config --global user.name "github-bot"
          git pull
          git add -A
          git commit -m "🤖 Auto Update Daily Quotations" || exit 0
          git push
